#!/bin/sh

set -e

PROTECTED_BRANCH="main|develop"

# If on the branch:
if { git branch -a | tee /dev/stderr | grep -Eq '^\*[[:blank:]]('"${PROTECTED_BRANCH}"')'; }; then
  echo "[ERROR] You can not commit on the \"${PROTECTED_BRANCH}\" branch."
  exit 1
fi

# cd repository root directory
cd "$(pwd)/$(git rev-parse --show-cdup)"

# run test
make test
